# Generated by Django 4.2.16 on 2024-12-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('signup', '0001_initial'),
	]

	operations = [
		migrations.AlterField(
			model_name='customuser',
			name='email',
			field=models.EmailField(max_length=200, unique=True),
		),
	]
